---
- hosts: all
  become: yes

  tasks:
    - name: Enable service sshd
      ansible.builtin.service:
        name: sshd.service
        enabled: yes

    - name: Install Git
      package:
        name: git
        state: latest

    - name: Clone repo Golang-myip
      git:
       repo: https://github.com/BastienBalaud/golang-myip.git
       dest: /golang-myip
       clone: yes
       update: yes

    - name: Modif port 80
      ansible.builtin.shell:
       cmd: sed -i 's/args.Port = 8080/args.Port = 80/g' /golang-myip/server.go

    - name : Install Make package
      package:
        name: make 
        state: latest

    - name: Install package GO
      package:
        name: go
        state: latest

    - name: Execut Makefile
      ansible.builtin.shell:
       cmd: make
       chdir: /golang-myip

    - name: Create golang directoryls -la
      ansible.builtin.template:
        src: template/golang.service
        dest: /etc/systemd/system/golang.service

    - name: Change SELinux
      ansible.builtin.shell:
       cmd: setenforce 0

    - name: Reboot Systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start service golang
      ansible.builtin.service:
        name: golang.service
        state: started

    - name: Enable service golang
      ansible.builtin.service:
        name: golang.service
        enabled: yes

    - name: Permissive SELinux
      ansible.posix.selinux:
       policy: targeted
       state: permissive

    - name: Clés Bastien
      authorized_key:
       user: root
       state: present
       key: https://github.com/BastienBalaud.keys
